// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzaxMELYTUm4EjA3VQj6Re7F0VnVTIIaA',
    appId: '1:886868159396:web:32097101bad22fbc81ef31',
    messagingSenderId: '886868159396',
    projectId: 'companytracker-e1f3c',
    authDomain: 'companytracker-e1f3c.firebaseapp.com',
    storageBucket: 'companytracker-e1f3c.firebasestorage.app',
    measurementId: 'G-R9YXJ6R3Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU3hnfNa1Rdqlw1c561XZdN5Vm2UgPWn0',
    appId: '1:886868159396:android:4152a96df79cadf681ef31',
    messagingSenderId: '886868159396',
    projectId: 'companytracker-e1f3c',
    storageBucket: 'companytracker-e1f3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC28jnFiqyMkt0Yeo-ntVqIPQ35HbrqKvo',
    appId: '1:886868159396:ios:b3bd351f48d8005c81ef31',
    messagingSenderId: '886868159396',
    projectId: 'companytracker-e1f3c',
    storageBucket: 'companytracker-e1f3c.firebasestorage.app',
    iosBundleId: 'com.example.companyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC28jnFiqyMkt0Yeo-ntVqIPQ35HbrqKvo',
    appId: '1:886868159396:ios:b3bd351f48d8005c81ef31',
    messagingSenderId: '886868159396',
    projectId: 'companytracker-e1f3c',
    storageBucket: 'companytracker-e1f3c.firebasestorage.app',
    iosBundleId: 'com.example.companyTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzaxMELYTUm4EjA3VQj6Re7F0VnVTIIaA',
    appId: '1:886868159396:web:c8d8dbf37ac7ec4c81ef31',
    messagingSenderId: '886868159396',
    projectId: 'companytracker-e1f3c',
    authDomain: 'companytracker-e1f3c.firebaseapp.com',
    storageBucket: 'companytracker-e1f3c.firebasestorage.app',
    measurementId: 'G-LZJBHBSTWL',
  );
}
